feat(controller): add irsa support
lablabs/terraform-aws-eks-argo-workflows pull request #2
Opened 2024-04-08 09:18 UTC by jaygridley

# Description

- Add support for controller IRSA. For example, this adds support for the controller to pull images from ECR to determine the image entrypoint/command (https://argo-workflows.readthedocs.io/en/stable/workflow-executors/#image-indexcache). This is also beneficial when the controller runs on an EKS node with limited instance metadata access, i.e. hop count = 1.

## Type of change

- [ ] A bug fix (PR prefix `fix`)
- [x] A new feature (PR prefix `feat`)
- [ ] A code change that neither fixes a bug nor adds a feature (PR prefix `refactor`)
- [ ] Adding missing tests or correcting existing tests (PR prefix `test`)
- [ ] Changes that do not affect the meaning of the code like white-spaces, formatting, missing semi-colons, etc. (PR prefix `style`)
- [ ] Changes to our CI configuration files and scripts (PR prefix `ci`)
- [ ] Documentation only changes (PR prefix `docs`)

## How Has This Been Tested?

- I added the IRSA role with the IAM policy, allowing the pulling of images from ECR when the controller is scheduled on a node with hop count = 1. Without IRSA, the controller cannot pull image metadata to determine the image entry point/command.

2024-04-08 16:07 UTC, dojci approved these changes
LGTM

2024-04-08 16:09 UTC, dojci requested changes
Missing controller irsa role attributes output

2024-04-08 16:09 UTC, dojci commented on variables-controller.tf
> +  default     = false
We can enable this by default

2024-04-09 05:51 UTC, jaygridley commented on variables-controller.tf
> +  default     = false
Agree, set to `true`

2024-04-09 05:52 UTC, merged